
CREATE DATABASE IF NOT EXISTS tchat;
USE tchat;

CREATE TABLE IF NOT EXISTS users(id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255),
email VARCHAR(255) UNIQUE,
password VARCHAR(255) );

CREATE TABLE IF NOT EXISTS messages(id INT PRIMARY KEY AUTO_INCREMENT,
sender VARCHAR(256),
receiver VARCHAR(256),
message TEXT,
date DATETIME);
